[package]
name = "pakajo"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed", rev = "1d217ee39d381ac101b7cf49d3d22451ac1093fe" }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = ["font-kit", "wayland", "x11"], rev = "1d217ee39d381ac101b7cf49d3d22451ac1093fe" }
gpui-component = { git = "https://github.com/longbridge/gpui-component", rev = "ba681dfc8892475c9bf51775fe8dd157b8f31aeb" }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component", rev = "ba681dfc8892475c9bf51775fe8dd157b8f31aeb" }
alpm = "5.0.2"
alpm-utils = "5.0.0"
pacmanconf = "3.1.0"
rust-embed = "8.11.0"
anyhow = "1.0.103"
regex = "1.12.4"
libc = "0.2"
nix = { version = "0.31", features = ["term"] }
signal-hook = { version = "0.3", features = ["iterator"] }
base64 = "0.22"
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = { version = "2", features = ["serde"] }
ureq = { version = "3", features = ["json"] }
flate2 = "1.0"
rusqlite = { version = "0.40", features = ["bundled"] }
tar = "0.4"
tempfile = "3"
srcinfo = "2.1.0"
wait-timeout = "0.2"
clap = { version = "4", features = ["derive"] }
inotify = { version = "0.11", default-features = false }
libcosmic = { git = "https://github.com/pop-os/libcosmic", rev = "dc1cf9f00cbe2902a52166492654bb9fee8a73d1", features = ["wgpu"] }

[features]
default = ["debug"]
debug = ["libcosmic/debug"]

[[bin]]
name = "pakajo-cosmic"
path = "src/cosmic.rs"
