[package]
name = "pakajo-search"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
thiserror = "2"
serde = { version = "1", features = ["derive"] }
bincode = { version = "2", features = ["serde"] }

[dev-dependencies]
tempfile = "3"
criterion = "0.8.2"
rusqlite = { version = "0.40", features = ["bundled"] }

[[bench]]
name = "search"
harness = false
