use std::path::Path;

use anyhow::Context as _;

pub fn read_from_dir(dir: &Path) -> anyhow::Result<::srcinfo::Srcinfo> {
    let path = dir.join(".SRCINFO");
    ::srcinfo::Srcinfo::from_path(&path)
        .with_context(|| format!("failed to read .SRCINFO at {}", path.display()))
}

pub fn generate(dir: &Path) -> anyhow::Result<::srcinfo::Srcinfo> {
    let output = std::process::Command::new("makepkg")
        .arg("--printsrcinfo")
        .current_dir(dir)
        .output()
        .context("failed to run makepkg --printsrcinfo")?;
    if !output.status.success() {
        anyhow::bail!("makepkg --printsrcinfo exited {}", output.status);
    }
    ::srcinfo::Srcinfo::from_buf(output.stdout.as_slice())
        .context("failed to parse srcinfo generated by makepkg")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_pkgver_pkgrel_and_source_from_buf() {
        let text = b"pkgbase = example\n\
                     pkgver = 1.5.0\n\
                     pkgrel = 5\n\
                     source = git+https://example.com/example.git\n\
                     \n\
                     pkgname = example\n";

        let srcinfo = ::srcinfo::Srcinfo::from_buf(&text[..]).expect("parses");
        assert_eq!(srcinfo.base.pkgbase, "example");
        assert_eq!(srcinfo.base.pkgver, "1.5.0");
        assert_eq!(srcinfo.base.pkgrel, "5");

        let sources: Vec<&str> = srcinfo.base.source.arch("x86_64").collect();
        assert_eq!(sources, vec!["git+https://example.com/example.git"]);
    }
}
